### ISSUE TITLE
Support open ended time interval

### ISSUE THREAD

**Issue by jcoyne** [inukshuk/edtf-ruby#32]
```ruby
EDTF.parse('2020/..')
nil
```

**Comment by inukshuk** [comment]
This library is still based from the EDTF version prior to the ISO standardisation. Open intervals used to be written as `2020/open` so that's what the parser should accept.

At some point this library will have to move to the new standard (I wrote the grammar for the newer JS version which should make this easy) but until then you'll need to use the old format.
